import type { Metadata } from 'next'
import './globals.css'
import { sans, serif } from '@/src/assets/fonts'


export const metadata: Metadata = {
  title: 'Rafi Gil Diaz',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${sans.variable} ${serif.variable}`}>
      <body>{children}</body>
    </html>
  )
}
